### ISSUE TITLE
lintpkg does not take relative paths as argument

### ISSUE THREAD

**Issue by ChrisAbela** [pprkut/lintpkg#6]
but I inserted one line and now it does:

--- lintpkg.orig 2017-01-20 12:15:41.699471760 +0000
+++ lintpkg  2017-01-20 13:19:24.493022010 +0000
@@ -437,6 +437,7 @@
   PKG_LISTING=$(cat $PACKAGE | $packagecompression -dc | $TAR ts)
   PKG_DETAILED_LISTING=$(cat $PACKAGE | $packagecompression -dc | $TAR tvs)
 
+  PACKAGE=$( realpath $PACKAGE )
   cd $WORKING_DIR
 
     ( umask 000 ; cat $PACKAGE | $packagecompression -dc | $TAR xf - 2> /dev/null )

**Comment by pprkut** [comment]
I had a similar fix for this already locally, but the outcome should be largely the same. Thanks! :)
